info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /member/:
    get:
      description: Reads handled by the mixins, and use permission_classes
      operationId: member_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      tags:
      - member
  /member/create_record/:
    post:
      description: Reads handled by the mixins, and use permission_classes
      operationId: member_create_record
      tags:
      - member
  /member/{id}/:
    get:
      description: Reads handled by the mixins, and use permission_classes
      operationId: member_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this member.
          title: id
          type: string
      tags:
      - member
    patch:
      description: Reads handled by the mixins, and use permission_classes
      operationId: member_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this member.
          title: id
          type: string
      tags:
      - member
    put:
      description: Reads handled by the mixins, and use permission_classes
      operationId: member_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this member.
          title: id
          type: string
      tags:
      - member
  /member/{id}/approve/:
    patch:
      description: approve the join request
      operationId: member_approve
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this member.
          title: id
          type: string
      tags:
      - member
  /member/{id}/leave/:
    patch:
      description: leave this team this is deletion but only to deactivate the record
      operationId: member_leave
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this member.
          title: id
          type: string
      tags:
      - member
  /member/{id}/make_admin/:
    patch:
      description: make the user an admin
      operationId: member_make_admin
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this member.
          title: id
          type: string
      tags:
      - member
  /status/create_record/:
    post:
      operationId: status_create_record
      tags:
      - status
  /status/{id}/:
    delete:
      operationId: status_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket status.
          title: ID
          type: integer
      tags:
      - status
    get:
      operationId: status_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket status.
          title: ID
          type: integer
      tags:
      - status
    patch:
      operationId: status_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket status.
          title: ID
          type: integer
      tags:
      - status
    put:
      operationId: status_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket status.
          title: ID
          type: integer
      tags:
      - status
  /status/{id}/list_team/:
    get:
      operationId: status_list_team
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket status.
          title: ID
          type: integer
      tags:
      - status
  /tag/create_record/:
    post:
      operationId: tag_create_record
      tags:
      - tag
  /tag/{id}/:
    delete:
      operationId: tag_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this tag.
          title: ID
          type: integer
      tags:
      - tag
    get:
      operationId: tag_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this tag.
          title: ID
          type: integer
      tags:
      - tag
    patch:
      operationId: tag_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this tag.
          title: ID
          type: integer
      tags:
      - tag
    put:
      operationId: tag_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this tag.
          title: ID
          type: integer
      tags:
      - tag
  /tag/{id}/list_team/:
    get:
      operationId: tag_list_team
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this tag.
          title: ID
          type: integer
      tags:
      - tag
  /team/:
    get:
      operationId: team_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      tags:
      - team
  /team/create_record/:
    post:
      operationId: team_create_record
      tags:
      - team
  /team/{id}/:
    delete:
      operationId: team_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this team.
          title: ID
          type: integer
      tags:
      - team
    get:
      operationId: team_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this team.
          title: ID
          type: integer
      tags:
      - team
    patch:
      operationId: team_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this team.
          title: ID
          type: integer
      tags:
      - team
    put:
      operationId: team_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this team.
          title: ID
          type: integer
      tags:
      - team
  /ticket-comment/:
    get:
      description: Basic crud should be pre-generated, so we only need to do the more
        complicated calls
      operationId: ticket-comment_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      tags:
      - ticket-comment
    post:
      description: Basic crud should be pre-generated, so we only need to do the more
        complicated calls
      operationId: ticket-comment_create
      tags:
      - ticket-comment
  /ticket-comment/recent_comments/:
    get:
      description: This call returns the first page of comments associated with the
        given team_id
      operationId: ticket-comment_recent_comments
      tags:
      - ticket-comment
  /ticket-comment/{id}/:
    delete:
      description: Basic crud should be pre-generated, so we only need to do the more
        complicated calls
      operationId: ticket-comment_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket comment.
          title: ID
          type: integer
      tags:
      - ticket-comment
    get:
      description: Basic crud should be pre-generated, so we only need to do the more
        complicated calls
      operationId: ticket-comment_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket comment.
          title: ID
          type: integer
      tags:
      - ticket-comment
    patch:
      description: Basic crud should be pre-generated, so we only need to do the more
        complicated calls
      operationId: ticket-comment_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket comment.
          title: ID
          type: integer
      tags:
      - ticket-comment
    put:
      description: Basic crud should be pre-generated, so we only need to do the more
        complicated calls
      operationId: ticket-comment_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket comment.
          title: ID
          type: integer
      tags:
      - ticket-comment
  /ticket/create_record/:
    post:
      description: This viewset automatically provides `list` and `detail` actions.
      operationId: ticket_create_record
      tags:
      - ticket
  /ticket/{id}/:
    get:
      description: This viewset automatically provides `list` and `detail` actions.
      operationId: ticket_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: ID
          type: integer
      - in: query
        name: search
        schema:
          description: A search term.
          title: Search
          type: string
      - in: query
        name: ordering
        schema:
          description: Which field to use when ordering the results.
          title: Ordering
          type: string
      tags:
      - ticket
    patch:
      description: This viewset automatically provides `list` and `detail` actions.
      operationId: ticket_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: ID
          type: integer
      - in: query
        name: search
        schema:
          description: A search term.
          title: Search
          type: string
      - in: query
        name: ordering
        schema:
          description: Which field to use when ordering the results.
          title: Ordering
          type: string
      tags:
      - ticket
    put:
      description: This viewset automatically provides `list` and `detail` actions.
      operationId: ticket_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: ID
          type: integer
      - in: query
        name: search
        schema:
          description: A search term.
          title: Search
          type: string
      - in: query
        name: ordering
        schema:
          description: Which field to use when ordering the results.
          title: Ordering
          type: string
      tags:
      - ticket
  /ticket/{id}/add_subticket/:
    patch:
      description: This viewset automatically provides `list` and `detail` actions.
      operationId: ticket_add_subticket
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: ID
          type: integer
      tags:
      - ticket
  /ticket/{id}/delete/:
    delete:
      description: deactivate this ticket this is deletion but only to deactivate
        the record
      operationId: ticket_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: ID
          type: integer
      tags:
      - ticket
  /ticket/{id}/list_team/:
    get:
      description: This viewset automatically provides `list` and `detail` actions.
      operationId: ticket_list_team
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: ID
          type: integer
      tags:
      - ticket
  /ticket/{id}/update_status/:
    patch:
      description: This viewset automatically provides `list` and `detail` actions.
      operationId: ticket_update_status
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: ID
          type: integer
      tags:
      - ticket
servers:
- url: ''
